### ISSUE TITLE
Shadow implementation?

### ISSUE THREAD

**Issue by ylluminate** [antiden/macOS-cursors-for-Windows#19]
Could you please implement a version of these with alpha transparency shadows that mimic that which is found in macOS?

**Comment by antiden** [comment]
@ylluminate This is standart Windows function. You can add shadow in mouse settings.

![alt text](https://www.isunshare.com/images/article/windows-10/2-ways-to-show-mouse-pointer-shadow-in-windows-10/select-enable-pointer-shadow-and-hit-ok.png "Cursor shadows")
