### ISSUE TITLE
150% Scale

### ISSUE THREAD

**Issue by lwskdesign** [antiden/macOS-cursors-for-Windows#2]
It would be great to have a 150% scale version.

**Comment by antiden** [comment]
> 

Hi, I will do it in the near future

**Comment by AbhigyanRanjan0505** [comment]
You can download the cur file and open it with [real world cursor editor](http://www.rw-designer.com/cursor-maker) then open the cur file and then edit that. you can resize by pressing X button selecting the cursor.

**Comment by AbhigyanRanjan0505** [comment]
For all 150% cursors, you can use the [real world cursor editor](http://www.rw-designer.com/cursor-maker).

**Comment by lwskdesign** [comment]
> > @lwskdesign
> 
> Hi, what screen resolution in your screen?

3840x2160
