### ISSUE TITLE
Hmm.. I removed my older version of mac cursors and installed the new one some bugs came front. 

### ISSUE THREAD

**Issue by AbhigyanRanjan0505** [antiden/macOS-cursors-for-Windows#20]
![Bug L](https://user-images.githubusercontent.com/71014464/119113430-b871b680-ba42-11eb-950e-ba7ed6e9ceb3.jpg)
![Bug XL](https://user-images.githubusercontent.com/71014464/119113434-b9a2e380-ba42-11eb-8cfb-f7ccb20211cb.jpg)
### **I saw that in L and XL versions 2 cursors were completely ruined...**
Hope you fix this issue.

**Comment by henriquemod** [comment]
That would be great

**Comment by antiden** [comment]
Thanks for bag. Please check.
