### ISSUE TITLE
Incorrect transparency

### ISSUE THREAD

**Issue by qo4on** [antiden/macOS-cursors-for-Windows#34]
Probably incorrect transparency in some cursors:
![image](https://user-images.githubusercontent.com/35609308/147798030-f492b4d9-6e4f-4f6b-bfe8-f15caf4e9c59.png)
And some hot spots:
![image](https://user-images.githubusercontent.com/35609308/147798263-785dd1a5-7b13-490a-bead-161a798d42ac.png)

**Comment by TheHunter1234** [comment]
Tbh to the naked eye, it is hardly unnoticeable unless you really look at it.

**Comment by antiden** [comment]
Hi, this is bug with smooth edges in Cursor program. Please check my new branch https://github.com/antiden/macOS-cursors-for-Windows/tree/fixes, you can install Normal cursors and check.

**Comment by qo4on** [comment]
Hi! Did you also fix the hot spots?

**Comment by antiden** [comment]
@qo4on yep
1. Made "Normal.cur" the cursor smaller
2. Busy and Working increased speed

**Comment by qo4on** [comment]
I use XL cursor. Not only normal, but also L and XL have the same problems.

**Comment by antiden** [comment]
@qo4on Please check Normal cursor, if ok, I made other versions.

**Comment by TheHunter1234** [comment]
> @qo4on yep
> 
> 1. Made "Normal.cur" the cursor smaller
> 2. Busy and Working increased speed
> 
> Do the cursors look sharper now?

From what I can tell, yes.

**Comment by TheHunter1234** [comment]
Nice

**Comment by antiden** [comment]
@qo4on yes, this bug program. Please contact with developers.

**Comment by qo4on** [comment]
What program do you use for editing cursors? I can't check them.
