### ISSUE TITLE
All cursor form https://codepen.io/chriscoyier/full/uCwfB + some fixes

### ISSUE THREAD

**Issue by nitin2953** [antiden/macOS-cursors-for-Windows#41]
All CSS cursors are not present
See at: [https://codepen.io/chriscoyier/full/uCwfB](https://codepen.io/chriscoyier/full/uCwfB)

Normal cursor tail look little too tall on white & little bit tall on black background
Please provide a Inverted color alternative to Normal cursor (like Windows)

↕ & ↔ look shorter then ↘↖ & ↗↙
3 Years ago I was not able to fix it, So I GIVE UP

I hope your project can 🙂!
BTW love to see this repo

[https://twitter.com/jonastreub/status/1465729123075121163](https://twitter.com/jonastreub/status/1465729123075121163)

**Comment by antiden** [comment]
Hi,

1. This is not standart Windows cursors. Codepen link for macos users. If you want change cursors in web, please use css like this `cursor: url("https://i.stack.imgur.com/ygtZg.png"), auto;`
2. In future i think will can change system Windows cursors
3. Size for Resize cursors is proportional, i think this is not bug.

This is request not issue, in the future please post your wishes in Descussion tab.

Thx! With regards antiden.
