### ISSUE TITLE
The Working cursor is not the actual one in macOS

### ISSUE THREAD

**Issue by iWajdi** [antiden/macOS-cursors-for-Windows#45]
the title is pretty much self explanatory the working cursor is not the same as in macOS, personally that's annoying  because the quality you give is amazing, but that's the only thing missing.

Found this thumbnail to show it to you

![image](https://user-images.githubusercontent.com/77938896/154294046-4f2b8604-fca4-4ba7-8d19-ea734272d4ac.png)

**Comment by antiden** [comment]
Hi,

I don't understand you, what you want?

**Comment by antiden** [comment]
Same as in MacOS Monterey. For you exit don't use these cursors =)

**Comment by iWajdi** [comment]
Dude, im not here to hate on your work, I just told you these look different, Ive been using macos for quite somrtimes and I know the difference. Dont take this the other way. I appreciate your effort and everything you did, I just said they are not the same.
