### ISSUE TITLE
Low resolution

### ISSUE THREAD

**Issue by pablotorres90** [antiden/macOS-cursors-for-Windows#53]
The icons are in low resolution.

**Comment by antiden** [comment]
Write in more detail what your screen resolution is, what cursors you use...

**Comment by mrpenguinb** [comment]
I've noticed the cursors are pretty blurry too (not scaled properly when they were created?).
I am using a 1440p monitor at 125% scaling and tried all three cursor sizes provided (with and without shadow as well).

**Comment by antiden** [comment]
Сursors only for 4K resolution
