### ISSUE TITLE
Windows 11 22H2 "The system cannot find the path specified."

### ISSUE THREAD

**Issue by garrywashere** [antiden/macOS-cursors-for-Windows#57]
I'm trying to install the cursor pack on my Laptop on a new install of windows but after the admin prompt, it just throws an error.
![image](https://user-images.githubusercontent.com/106199295/203754319-9bf35e17-dc00-4163-9845-bcfefa6f1cde.png)
Можешь помочь? Спасибо братан...

**Comment by antiden** [comment]
@garrywashere
I will check, perhaps the settings of the registry have changed. You can just copy the desired folder with cursors to the folder C:\Windows\Cursors and select in mouse settings.

**Comment by antiden** [comment]
Found this problem on my virtual machine. Here it is no longer a problem of cursors, but virtual settings. On a normal computer, everything is installed without problems. I am closing this issue.
