### ISSUE TITLE
Dark theme IBeam

### ISSUE THREAD

**Issue by rskvprd** [antiden/macOS-cursors-for-Windows#61]
macOS has a white IBeam which is better visible in dark mode. Unfortunately you don't have this IBeam :(
White IBeam in dark theme
![image](https://user-images.githubusercontent.com/70895154/230465349-956b63a5-de68-4e48-a8b0-33f3acae1a1f.png)
Dark IBeam in dark theme
![image](https://user-images.githubusercontent.com/70895154/230465595-5c95b65d-ec86-40ec-a283-f2e38c1be963.png)

**Comment by antiden** [comment]
Hi @rskvprd,

Please tell me your screen resolution and name of cursor folder.

**Comment by rskvprd** [comment]
> screen resolution

Screen Resolution: **_1920x1080_**.
> name of cursor folder

I didn’t quite understand what folder name you wanted to know and why, so I’ll write the basic information.
These cursors are installed in the **_C:/Windows/Cursors_** folder (like all other cursors).
The **_macOS-cursors-for-windows-main_** folder with the original cursors (not installed) is stored in the same folder as the installed ones.
I installed cursors from **_"1. Sierra and newer"/"1.No Shadow"/"1.Normal"_** folder using **_Install.inf_** and use them.

P.S. I would just like to have a light version of IBeam (**_Text.cur_** in your case) in this cursor package.

**Comment by antiden** [comment]
@rskvprd Thx. Cursors ONLY for 4k displays with 3840×2160 px.

**Comment by rskvprd** [comment]
Let's pretend I have a 4K monitor. There is no white text pointer in the pack anyway
