### ISSUE TITLE
Inf file opens in notepad

### ISSUE THREAD

**Issue by VityaSchel** [antiden/macOS-cursors-for-Windows#62]
Hello! I have tiny11 version of Windows 11 and I can't execute INF file since it opens in notepad. I tried fixing it by deassociating with notepad, but there seems to be no program on windows that can run inf files. ALso I don't understand how to manually load these cursor icons to cursor settings window. please help!

**Comment by VityaSchel** [comment]
I figured out how to install it (right click -> install), but now it gives me "Installation failed" error

**Comment by antiden** [comment]
@VityaSchel Hi, you can just copy the desired folder with cursors to the folder C:\Windows\Cursors and select in mouse settings.
