### ISSUE TITLE
Unable to install inf file

### ISSUE THREAD

**Issue by NotTitanskull** [antiden/macOS-cursors-for-Windows#65]
When trying to install "Install.inf" it only replies with "Installation failed."

I am using Windows 11 through a virtual machine on Parallels.
The computer that I am using is a MacBook Air (M1) (Late 2020) Model with 16 GB of RAM.
<img width="1440" alt="Screenshot 2024-01-22 at 2 54 58 PM" src="https://github.com/antiden/macOS-cursors-for-Windows/assets/71719735/aa072af5-9d81-4f27-8df3-7c09b4a851b8">

**Comment by antiden** [comment]
Hi, this is from #57 

> Here it is no longer a problem of cursors, but virtual settings. On a normal computer, everything is installed without problems.

**Comment by ShgnanWu** [comment]
Did you solved this problem? I also tried to install some 'xxx.inf' driver files in the Windows 11 through a virtual machine on Parallels.

**Comment by anaisbetts** [comment]
This also doesn't work on ARM64 machines that are not virtualized. I also question why a virtual machine would make a difference here?
