### ISSUE TITLE
Possibly missing some cursors?

### ISSUE THREAD

**Issue by LoganDark** [antiden/macOS-cursors-for-Windows#67]
This looks to be missing some cursors like the grab cursor (hand that closes when you click on stuff). That's the one that's low-quality and pixelated especially on 4K displays, and it doesn't seem to be included here. Is it possible for you to add it?

**Comment by antiden** [comment]
Hi @LoganDark,

Yes, I opened a discussion [topic](https://github.com/antiden/macOS-cursors-for-Windows/discussions/43), these are system cursors and when I have more information on how to change them, I will do it.
